/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApplicationParts;

import BPlusTree.BPlusTreeComponent;
import BPlusTree.FileCommander;
import ConvertTypes.PropertyKey;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author korenciak.marek
 */
public class GUIApplication extends javax.swing.JFrame {

    /**
     * Creates new form GUIApplication
     */
    public GUIApplication() {
        initComponents();
        setLocationRelativeTo(null);
        systemMessage.setVisible(false);

        FMTable.addPropertyChangeListener(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                int row = FMTable.getSelectedRow();
                int column = FMTable.getSelectedColumn();
                Object[] temp = applicationLogic.getBorder(row);
                if (column == 0) {
                    return;
                }
                if (column == 1 || column == 3) {

                    if (((Double) applicationLogic.getBorder(row)[column - 1]).compareTo((Double) FMTable.getValueAt(row, column)) == 0) {
                        return;
                    } else {
                        temp[column - 1] = FMTable.getValueAt(row, column);
                    }
                }
                if (column == 2 || column == 4) {
                    if (((String) applicationLogic.getBorder(row)[column - 1]).compareTo((String) FMTable.getValueAt(row, column)) == 0) {
                        return;
                    } else {
                        if (((String) FMTable.getValueAt(row, column)).compareTo("true") == 0 || ((String) FMTable.getValueAt(row, column)).compareTo("false") == 0) {
                            temp[column - 1] = FMTable.getValueAt(row, column);
                        } else {
                            fillTable(applicationLogic.getBorders());
                            return;
                        }
                    }
                }
                if (((String) temp[3]).compareTo("true") == 0) {
                    temp[3] = true;
                } else {
                    temp[3] = false;
                }
                if (((String) temp[1]).compareTo("true") == 0) {
                    temp[1] = true;
                } else {
                    temp[1] = false;
                }
                applicationLogic.updateBorderPoint(row, (Boolean) temp[3], (Double) temp[2], (Boolean) temp[1], (Double) temp[0]);
                fillTable(applicationLogic.getBorders());
            }
        });

        mainTab.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                if (mainTab.getSelectedIndex() == 2) {
                    promiscuousMode();
                }
            }
        });
        
        LinkedList<JTabbedPane> tabbedPanes = new LinkedList<>();
        tabbedPanes.add(mainTab);
        tabbedPanes.add(jTabbedPane2);
        tabbedPanes.add(visitorTab);
        
        for (JTabbedPane pane : tabbedPanes) {
            pane.addChangeListener(new ChangeListener() {
                int selected = pane.getSelectedIndex();

                @Override
                public void stateChanged(ChangeEvent e) {
                    if (pane.getSelectedIndex() != selected) {
                        selected = pane.getSelectedIndex();
                        reserSystemMessage();
                    }
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        mainTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addCadasterName = new javax.swing.JTextField();
        addPropertyNumber = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addLatitudeAxis = new javax.swing.JTextField();
        addLatitudeNorth = new javax.swing.JRadioButton();
        addLatitudeSouth = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        addLongitudeAxis = new javax.swing.JTextField();
        addLongitudeWest = new javax.swing.JRadioButton();
        addLongitudeEast = new javax.swing.JRadioButton();
        addBorderPointButton = new javax.swing.JButton();
        savePropertyButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FMfindCadasterName = new javax.swing.JTextField();
        FMfindPropertyNumber = new javax.swing.JTextField();
        FMfindButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FMaddBorderButton = new javax.swing.JButton();
        FMaddBorderLatitudeAxis = new javax.swing.JTextField();
        FMaddBorderLongitudeAxis = new javax.swing.JTextField();
        FMaddBorderLatitudeNorth = new javax.swing.JRadioButton();
        FMaddBorderLatitudeSouth = new javax.swing.JRadioButton();
        FMaddBorderLongitudeWest = new javax.swing.JRadioButton();
        FMaddBorderLongitudeEast = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        FMdeleteBorderIndex = new javax.swing.JTextField();
        FMdeleteBorderButton = new javax.swing.JButton();
        FMcommitModifyButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FMTable = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FMCadasterName = new javax.swing.JLabel();
        FMPropertyNumber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FMDescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        deleteCadasterName = new javax.swing.JTextField();
        deletePropertyNumber = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        visitorTab = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        visitorBlockInspectAddress = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        visitorFreeBlockPreviousButton = new javax.swing.JButton();
        visitorFreeBlocksNextButton = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        visitorLeafInspectNext = new javax.swing.JButton();
        visitorLeafInspectPrevious = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        visitorInfoTextArea = new javax.swing.JTextArea();
        jPanel23 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        visitorLeafCompNumber = new javax.swing.JLabel();
        visitorDataPartLength = new javax.swing.JLabel();
        visitorFirstOfChaining = new javax.swing.JLabel();
        visitorParentAddress = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        visitorEmpty = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        generatePropertiesPerCadaster = new javax.swing.JTextField();
        generateCadasterCount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        fileNameChange = new javax.swing.JTextField();
        changeFileName = new javax.swing.JButton();
        systemMessage = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Add basic information"));

        jLabel1.setText("Cadaster name");

        jLabel2.setText("Property number");

        addCadasterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCadasterNameActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addPropertyNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(addCadasterName))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(addButton)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addCadasterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addPropertyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(addButton)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Border point"));

        jLabel7.setText("Latitude axis");

        addLatitudeNorth.setText("North");
        addLatitudeNorth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLatitudeNorthActionPerformed(evt);
            }
        });

        addLatitudeSouth.setText("South");
        addLatitudeSouth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLatitudeSouthActionPerformed(evt);
            }
        });

        jLabel8.setText("Longitude axis");

        addLongitudeWest.setText("West");
        addLongitudeWest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLongitudeWestActionPerformed(evt);
            }
        });

        addLongitudeEast.setText("East");
        addLongitudeEast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLongitudeEastActionPerformed(evt);
            }
        });

        addBorderPointButton.setText("Add border point");
        addBorderPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBorderPointButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(addLatitudeNorth)
                    .addComponent(jLabel8)
                    .addComponent(addLongitudeWest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLongitudeEast)
                    .addComponent(addLatitudeSouth)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addLongitudeAxis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(addLatitudeAxis)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBorderPointButton)
                .addGap(94, 94, 94))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addLatitudeAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLatitudeNorth)
                    .addComponent(addLatitudeSouth))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addLongitudeAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLongitudeWest)
                    .addComponent(addLongitudeEast))
                .addGap(18, 18, 18)
                .addComponent(addBorderPointButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        savePropertyButton.setText("Save Property");
        savePropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePropertyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(savePropertyButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(savePropertyButton)
                .addGap(0, 165, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add", jPanel9);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Find property"));

        jLabel11.setText("Cadaster name");

        jLabel12.setText("Property number");

        FMfindButton.setText("Find");
        FMfindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMfindButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FMfindCadasterName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FMfindPropertyNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(FMfindButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(FMfindCadasterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(FMfindPropertyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FMfindButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Add border point"));

        jLabel13.setText("Latitude axis");

        jLabel14.setText("Longitude axis");

        FMaddBorderButton.setText("Add border point");
        FMaddBorderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMaddBorderButtonActionPerformed(evt);
            }
        });

        FMaddBorderLatitudeNorth.setText("North");

        FMaddBorderLatitudeSouth.setText("South");

        FMaddBorderLongitudeWest.setText("West");

        FMaddBorderLongitudeEast.setText("East");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(FMaddBorderLatitudeNorth))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FMaddBorderLatitudeSouth)
                                    .addComponent(FMaddBorderLatitudeAxis, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FMaddBorderLongitudeAxis, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(FMaddBorderLongitudeWest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FMaddBorderLongitudeEast)
                        .addGap(117, 117, 117))))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(FMaddBorderButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(FMaddBorderLatitudeAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FMaddBorderLatitudeSouth)
                    .addComponent(FMaddBorderLatitudeNorth))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(FMaddBorderLongitudeAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FMaddBorderLongitudeWest)
                    .addComponent(FMaddBorderLongitudeEast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(FMaddBorderButton)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete border point"));

        jLabel6.setText("Index of border point");

        FMdeleteBorderButton.setText("Delete border point");
        FMdeleteBorderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMdeleteBorderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(FMdeleteBorderIndex)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(FMdeleteBorderButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(FMdeleteBorderIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(FMdeleteBorderButton)
                .addContainerGap())
        );

        FMcommitModifyButton.setText("Commit modify");
        FMcommitModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMcommitModifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(FMcommitModifyButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FMcommitModifyButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Find & Modify", jPanel10);

        FMTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Latitude axis", "Latitude North", "Longitude axis", "Longitude West"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(FMTable);

        jLabel3.setText("Cadaster name");

        jLabel4.setText("Property number");

        jLabel5.setText("Description");

        FMCadasterName.setText("jLabel6");

        FMPropertyNumber.setText("jLabel6");

        FMDescription.setColumns(20);
        FMDescription.setRows(5);
        jScrollPane1.setViewportView(FMDescription);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FMPropertyNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FMCadasterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FMCadasterName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FMPropertyNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        mainTab.addTab("Add", jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete property"));

        jLabel9.setText("Cadaster name");

        jLabel10.setText("Property number");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteCadasterName)
                            .addComponent(deletePropertyNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(deleteButton)))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(deleteCadasterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(deletePropertyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 493, Short.MAX_VALUE))
        );

        mainTab.addTab("Delete", jPanel3);

        jLabel22.setText("Block address");

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Pervious");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(previousButton)
                    .addComponent(jLabel22))
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(visitorBlockInspectAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton)
                        .addContainerGap())))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(goButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(visitorBlockInspectAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(goButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButton)
                    .addComponent(nextButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        visitorTab.addTab("Block inspect", jPanel19);

        visitorFreeBlockPreviousButton.setText("Previous");
        visitorFreeBlockPreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorFreeBlockPreviousButtonActionPerformed(evt);
            }
        });

        visitorFreeBlocksNextButton.setText("Next");
        visitorFreeBlocksNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorFreeBlocksNextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visitorFreeBlockPreviousButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(visitorFreeBlocksNextButton)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitorFreeBlockPreviousButton)
                    .addComponent(visitorFreeBlocksNextButton))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        visitorTab.addTab("Free blocks", jPanel20);

        visitorLeafInspectNext.setText("Next");
        visitorLeafInspectNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorLeafInspectNextActionPerformed(evt);
            }
        });

        visitorLeafInspectPrevious.setText("Previous");
        visitorLeafInspectPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorLeafInspectPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visitorLeafInspectPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(visitorLeafInspectNext)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitorLeafInspectNext)
                    .addComponent(visitorLeafInspectPrevious))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        visitorTab.addTab("Leaf inspect", jPanel21);

        visitorInfoTextArea.setColumns(20);
        visitorInfoTextArea.setRows(5);
        jScrollPane3.setViewportView(visitorInfoTextArea);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        jLabel23.setText("Parent address");

        jLabel24.setText("First of chaining");

        jLabel26.setText("Data part length");

        jLabel27.setText("Leaf component number");

        visitorLeafCompNumber.setText("jLabel28");

        visitorDataPartLength.setText("jLabel28");

        visitorFirstOfChaining.setText("jLabel28");

        visitorParentAddress.setText("visitorParentAddress");

        jLabel25.setText("First empty block");

        visitorEmpty.setText("jLabel28");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25))
                .addGap(33, 33, 33)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visitorLeafCompNumber)
                    .addComponent(visitorFirstOfChaining)
                    .addComponent(visitorParentAddress)
                    .addComponent(visitorDataPartLength)
                    .addComponent(visitorEmpty))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(visitorParentAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(visitorFirstOfChaining))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(visitorDataPartLength))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(visitorLeafCompNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(visitorEmpty))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(visitorTab, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visitorTab, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTab.addTab("File visitor", jPanel4);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setText("Cadaster count");

        jLabel21.setText("Properties per cadaster");

        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generatePropertiesPerCadaster, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(generateCadasterCount)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jButton2)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(generateCadasterCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(generatePropertiesPerCadaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 514, Short.MAX_VALUE))
        );

        mainTab.addTab("Data generator", jPanel8);

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("File name change"));

        jLabel28.setText("New file name");

        changeFileName.setText("Change and load");
        changeFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFileNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(fileNameChange, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(changeFileName)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(fileNameChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(changeFileName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 527, Short.MAX_VALUE))
        );

        mainTab.addTab("Change file name", jPanel24);

        systemMessage.setText("jLabel20");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(systemMessage)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCadasterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCadasterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCadasterNameActionPerformed

    private void FMfindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMfindButtonActionPerformed
        if (filledTextField(FMfindCadasterName) && filledTextField(FMfindPropertyNumber)) {
            if (applicationLogic.find(convertInteger(FMfindPropertyNumber), FMfindCadasterName.getText())) {
                updateGUI();
                setSystemMessageNormal("Property found.");
            } else {
                applicationLogic.resetProperty();
                updateGUI();
                setSystemMessageError("Property not found.");
            }
        } else {
            setSystemMessageError("Fill text fields.");
        }
    }//GEN-LAST:event_FMfindButtonActionPerformed

    private void addLatitudeSouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLatitudeSouthActionPerformed
        addLatitudeNorth.setSelected(false);
    }//GEN-LAST:event_addLatitudeSouthActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (filledTextField(addCadasterName) && filledTextField(addPropertyNumber)) {
            applicationLogic.createProperty(convertInteger(addPropertyNumber), addCadasterName.getText(), "");
            updateGUI();
            setSystemMessageNormal("New combination cadaster name, property number created.");
        } else {
            setSystemMessageError("Fill text fields.");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void addLatitudeNorthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLatitudeNorthActionPerformed
        addLatitudeSouth.setSelected(false);
    }//GEN-LAST:event_addLatitudeNorthActionPerformed

    private void addLongitudeWestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLongitudeWestActionPerformed
        addLongitudeEast.setSelected(false);
    }//GEN-LAST:event_addLongitudeWestActionPerformed

    private void addLongitudeEastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLongitudeEastActionPerformed
        addLongitudeWest.setSelected(false);
    }//GEN-LAST:event_addLongitudeEastActionPerformed

    private void addBorderPointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBorderPointButtonActionPerformed
        if (chackRadioButton(addLongitudeWest, addLongitudeEast) && chackRadioButton(addLatitudeNorth, addLatitudeSouth)
                && filledTextField(addLatitudeAxis) && filledTextField(addLongitudeAxis)) {
            if (applicationLogic.addBorderPoint(addLongitudeWest.isSelected(), convertDouble(addLongitudeAxis),
                    addLatitudeNorth.isSelected(), convertDouble(addLatitudeAxis))) {
                setSystemMessageNormal("Border point add.");
            } else {
                setSystemMessageNormal("Border not add. This property has max number of border points.");
            }
            updateGUI();
        } else {
            setSystemMessageError("Fill all attributes.");
        }
    }//GEN-LAST:event_addBorderPointButtonActionPerformed

    private void savePropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePropertyButtonActionPerformed
        applicationLogic.updateDescription(FMDescription.getText());
        if (applicationLogic.insertProperty()) {
            setSystemMessageNormal("Property inserted.");
            applicationLogic.resetProperty();
        } else {
            setSystemMessageNormal("Property with this key exists yet.");
        }
        updateGUI();
    }//GEN-LAST:event_savePropertyButtonActionPerformed

    private void FMaddBorderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMaddBorderButtonActionPerformed
        if (chackRadioButton(FMaddBorderLatitudeNorth, FMaddBorderLatitudeSouth) && chackRadioButton(FMaddBorderLongitudeEast, FMaddBorderLongitudeWest)
                && filledTextField(FMaddBorderLatitudeAxis) && filledTextField(FMaddBorderLongitudeAxis)) {
            if (applicationLogic.addBorderPoint(FMaddBorderLongitudeWest.isSelected(), convertDouble(FMaddBorderLongitudeAxis),
                    FMaddBorderLatitudeNorth.isSelected(), convertDouble(FMaddBorderLatitudeAxis))) {
                setSystemMessageNormal("Border point add.");
            } else {
                setSystemMessageNormal("Border not add. This property has max number of border points.");
            }
            updateGUI();
        } else {
            setSystemMessageError("Fill all attributes.");
        }
    }//GEN-LAST:event_FMaddBorderButtonActionPerformed

    private void FMdeleteBorderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMdeleteBorderButtonActionPerformed
        if (filledTextField(FMdeleteBorderIndex)) {
            if (applicationLogic.deleteBorderPoint(convertInteger(FMdeleteBorderIndex))) {
                setSystemMessageNormal("Border point deleted");
                updateGUI();
            } else {
                setSystemMessageNormal("No border point with this index.");
            }
        } else {
            setSystemMessageError("Fill atribute.");
        }
    }//GEN-LAST:event_FMdeleteBorderButtonActionPerformed

    private void FMcommitModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMcommitModifyButtonActionPerformed
        applicationLogic.updateDescription(FMDescription.getText());
        if (applicationLogic.commitUpdate()) {
            setSystemMessageNormal("Commit complete");
        } else {
            setSystemMessageNormal("Commit uncomplete.");
        }
    }//GEN-LAST:event_FMcommitModifyButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (filledTextField(generateCadasterCount) && filledTextField(generatePropertiesPerCadaster)) {
            applicationLogic.generateData(convertInteger(generateCadasterCount), convertInteger(generatePropertiesPerCadaster));
        } else {
            setSystemMessageError("Fill all attributes.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (filledTextField(deleteCadasterName) && filledTextField(deletePropertyNumber)) {
            if (applicationLogic.delete(convertInteger(deletePropertyNumber), deleteCadasterName.getText())) {
                setSystemMessageNormal("Property deleted.");
            } else {
                setSystemMessageNormal("Property not found.");
            }
        } else {
            setSystemMessageError("Fill all attributes.");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        if (parentAddress == -1) {
            return;
        }
        address = Long.parseLong(visitorBlockInspectAddress.getText());
        visitorInfoTextArea.setText(deserialize(address));
    }//GEN-LAST:event_goButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        if (parentAddress == -1) {
            return;
        }
        if (address - serializedLength >= 0) {
            address -= serializedLength;
            visitorInfoTextArea.setText(deserialize(address));
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (parentAddress == -1) {
            return;
        }
        if (address + serializedLength < commander.fileSize()) {
            address += serializedLength;
            visitorInfoTextArea.setText(deserialize(address));
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void visitorFreeBlockPreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorFreeBlockPreviousButtonActionPerformed
        if (parentAddress == -1) {
            return;
        }
        if (emptyArrayIndex != -1) {
            if (emptyArrayIndex != 0) {
                emptyArrayIndex--;
                visitorInfoTextArea.setText(empty.get(emptyArrayIndex) + "");
            } else {
                visitorInfoTextArea.setText(empty.get(emptyArrayIndex) + "");
            }
        }
    }//GEN-LAST:event_visitorFreeBlockPreviousButtonActionPerformed

    private void visitorFreeBlocksNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorFreeBlocksNextButtonActionPerformed
        if (parentAddress == -1) {
            return;
        }
        if (emptyArrayIndex != -1) {
            if (emptyArrayIndex != empty.size() - 1) {
                emptyArrayIndex++;
                visitorInfoTextArea.setText(empty.get(emptyArrayIndex) + "");
            } else {
                visitorInfoTextArea.setText(empty.get(emptyArrayIndex) + "");
            }
        }
    }//GEN-LAST:event_visitorFreeBlocksNextButtonActionPerformed

    private void visitorLeafInspectNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorLeafInspectNextActionPerformed
        if (parentAddress == -1) {
            return;
        }
        if (visit != null) {
            if (!visit.getInternal()) {
                if (visit.getRightChaining() != -1) {
                    address = visit.getRightChaining();
                    visitorInfoTextArea.setText(deserialize(address));
                } else {
                    visitorInfoTextArea.setText("This node is last of chaining.");
                }
            } else {
                visitorInfoTextArea.setText("This node is not leaf.");
            }
        }
    }//GEN-LAST:event_visitorLeafInspectNextActionPerformed

    private void visitorLeafInspectPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorLeafInspectPreviousActionPerformed
        if (parentAddress == -1) {
            return;
        }
        if (visit != null) {
            if (!visit.getInternal()) {
                if (visit.getLeftChaining() != -1) {
                    address = visit.getLeftChaining();
                    visitorInfoTextArea.setText(deserialize(address));
                } else {
                    visitorInfoTextArea.setText("This node is first of chaining.");
                }
            } else {
                visitorInfoTextArea.setText("This node is not leaf.");
            }
        }
    }//GEN-LAST:event_visitorLeafInspectPreviousActionPerformed

    private void changeFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFileNameActionPerformed
        if (filledTextField(fileNameChange)) {
            fileName = fileNameChange.getText();
            applicationLogic = new ApplicationController(fileName, deleteWholeBlocks);
            setSystemMessageNormal("File changed.");
        } else {
            setSystemMessageError("Fill file name atribute.");
        }
    }//GEN-LAST:event_changeFileNameActionPerformed

    private String fileName = "PropertiesStored.df";
    boolean deleteWholeBlocks = false;
    private ApplicationController applicationLogic = new ApplicationController(fileName, deleteWholeBlocks);

    private long parentAddress = -1;
    private long firstOfChaining = -1;
    private int dataPartLength = -1;
    private int leafComponentNumber = -1;
    FileCommander commander = null;
    private long address = 36;
    private int serializedLength = -1;
    private ArrayList<Long> empty = null;
    private int emptyArrayIndex = -1;
    private BPlusTreeComponent visit = null;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIApplication().setVisible(true);
            }
        });
    }

    private void updateGUI() {
        Object[] temp = applicationLogic.getProperty();
        FMCadasterName.setText((String) temp[0]);
        FMPropertyNumber.setText((String) temp[1]);
        FMDescription.setText((String) temp[2]);

        fillTable(applicationLogic.getBorders());
    }

    private boolean filledTextField(JTextField textField) {
        if (textField.getText().compareTo("") == 0) {
            return false;
        }
        if (textField.getText() == null) {
            return false;
        }
        return true;
    }

    private boolean chackRadioButton(JRadioButton first, JRadioButton second) {
        if ((first.isSelected() == true && second.isSelected() == false) || (first.isSelected() == false && second.isSelected() == true)) {
            return true;
        }
        return false;
    }

    private Integer convertInteger(JTextField textField) {
        try {
            return Integer.parseInt(textField.getText());
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private Double convertDouble(JTextField textField) {
        try {
            return Double.parseDouble(textField.getText());
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private void setSystemMessageNormal(String msg) {
        systemMessage.setForeground(Color.BLACK);
        systemMessage.setText(msg);
        systemMessage.setVisible(true);
    }

    private void setSystemMessageError(String msg) {
        systemMessage.setForeground(Color.RED);
        systemMessage.setText(msg);
        systemMessage.setVisible(true);
    }
    
    private void reserSystemMessage(){
        systemMessage.setVisible(false);
    }

    private void fillTable(Object[][] tableData) {
        DefaultTableModel tableModel = (DefaultTableModel) FMTable.getModel();
        tableModel.setRowCount(0);
        for (Object[] row : tableData) {
            tableModel.addRow(row);
        }
        FMTable.setModel(tableModel);
    }

    private void promiscuousMode() {
        commander = new FileCommander(fileName, 0, false, deleteWholeBlocks);           //pre visit ineho suboru tu zmen meno
        serializedLength = commander.getSerializedLength();
        commander = new FileCommander(fileName, serializedLength, false, deleteWholeBlocks);     //aj tu a potom este v metode deserialize nizsie
        parentAddress = commander.getRootAddress();
        firstOfChaining = commander.getFirstOfChainedList();
        leafComponentNumber = commander.getLeafComponentNumber();
        dataPartLength = commander.getDataByteArrayLength();
        address = parentAddress;
        empty = commander.getEmpty();

        if (empty.size() == 0) {
            visitorEmpty.setText("-1");
            emptyArrayIndex = -1;
        } else {
            visitorEmpty.setText(empty.get(0) + "");
            emptyArrayIndex = 0;
        }

        visitorParentAddress.setText(parentAddress + "");
        visitorDataPartLength.setText(dataPartLength + "");
        visitorFirstOfChaining.setText(firstOfChaining + "");
        visitorLeafCompNumber.setText(leafComponentNumber + "");
        if (parentAddress != -1) {
            visitorInfoTextArea.setText(deserialize(address));
        } else {
            visitorInfoTextArea.setText("File is empty.");
        }
    }

    public String deserialize(long address) {
        String output = "Address: " + address + "\n";
        output += "Node type: ";                            //o riadok nizsie zmen typ a dlzku serializovaneho kluza na konci
        visit = new BPlusTreeComponent(PropertyKey.class, 0, commander, false, serializedLength, dataPartLength, new PropertyKey().convertedLength());
        visit.deserialize(commander.read(address), address);
        if (visit.getInternal()) {
            output += "internal\n";
        } else {
            output += "leaf\n";
        }

        output += "Record number: " + visit.getRecordNumber() + "\n";
        output += "Records inserted: " + visit.getKeysCount() + "\n";
        output += "Key list: \n";
        for (int i = 0; i < visit.getKeysCount(); i++) {
            output += visit.getKeyAtIndex(i) + "\n";
        }
        output += "\n";
        if (visit.getInternal()) {
            for (int i = 0; i < visit.getKeysCount() + 1; i++) {
                output += visit.getSonAtIndex(i) + "\n";
            }
        }
        output += "\n";
        output += "Parent address: " + visit.getParent() + "\n";
        output += "Right chaining address: " + visit.getRightChaining() + "\n";
        output += "Left chaining address: " + visit.getLeftChaining() + "\n";

        return output;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FMCadasterName;
    private javax.swing.JTextArea FMDescription;
    private javax.swing.JLabel FMPropertyNumber;
    private javax.swing.JTable FMTable;
    private javax.swing.JButton FMaddBorderButton;
    private javax.swing.JTextField FMaddBorderLatitudeAxis;
    private javax.swing.JRadioButton FMaddBorderLatitudeNorth;
    private javax.swing.JRadioButton FMaddBorderLatitudeSouth;
    private javax.swing.JTextField FMaddBorderLongitudeAxis;
    private javax.swing.JRadioButton FMaddBorderLongitudeEast;
    private javax.swing.JRadioButton FMaddBorderLongitudeWest;
    private javax.swing.JButton FMcommitModifyButton;
    private javax.swing.JButton FMdeleteBorderButton;
    private javax.swing.JTextField FMdeleteBorderIndex;
    private javax.swing.JButton FMfindButton;
    private javax.swing.JTextField FMfindCadasterName;
    private javax.swing.JTextField FMfindPropertyNumber;
    private javax.swing.JButton addBorderPointButton;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addCadasterName;
    private javax.swing.JTextField addLatitudeAxis;
    private javax.swing.JRadioButton addLatitudeNorth;
    private javax.swing.JRadioButton addLatitudeSouth;
    private javax.swing.JTextField addLongitudeAxis;
    private javax.swing.JRadioButton addLongitudeEast;
    private javax.swing.JRadioButton addLongitudeWest;
    private javax.swing.JTextField addPropertyNumber;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton changeFileName;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField deleteCadasterName;
    private javax.swing.JTextField deletePropertyNumber;
    private javax.swing.JTextField fileNameChange;
    private javax.swing.JTextField generateCadasterCount;
    private javax.swing.JTextField generatePropertiesPerCadaster;
    private javax.swing.JButton goButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton savePropertyButton;
    private javax.swing.JLabel systemMessage;
    private javax.swing.JTextField visitorBlockInspectAddress;
    private javax.swing.JLabel visitorDataPartLength;
    private javax.swing.JLabel visitorEmpty;
    private javax.swing.JLabel visitorFirstOfChaining;
    private javax.swing.JButton visitorFreeBlockPreviousButton;
    private javax.swing.JButton visitorFreeBlocksNextButton;
    private javax.swing.JTextArea visitorInfoTextArea;
    private javax.swing.JLabel visitorLeafCompNumber;
    private javax.swing.JButton visitorLeafInspectNext;
    private javax.swing.JButton visitorLeafInspectPrevious;
    private javax.swing.JLabel visitorParentAddress;
    private javax.swing.JTabbedPane visitorTab;
    // End of variables declaration//GEN-END:variables
}
